name: Build And Release
on:
  push:
    branches: [ master ]
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment: Production
        steps:
            - name: Checkout
              uses: actions/checkout@master
              with:
                  persist-credentials: false
                  submodules: recursive

            - name: Add Chinese Fonts
              run: |
                  sudo apt-get install ttf-mscorefonts-installer
                  sudo apt-get install fontconfig
                  fc-list :lang=zh
                  ls -lh /usr/share/fonts/
                  cp -rf ./static/fonts/* /usr/share/fonts/
                  mkfontscale
                  mkfontdir
                  fc-cache
                  fc-list :lang=zh

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Build
              run: |
                  npm install -g yarn
                  yarn cache clean
                  export NODE_OPTIONS=--max-old-space-size=8192
                  yarn && yarn build
                  touch build/.dummy
                  cp .asf-site.yaml ./build/.asf.yaml
                  cp versions.json ./build/
                  ls build
                  export DORIS_COMMIT=`git rev-parse HEAD`

            #     - name: Generate PDF
            #       run: |
            #         npx vitpress-generate-pdf --initialDocURLs="https://doris.apache.org/docs/dev/get-starting/" --paginationSelector=".pagination-nav__link--next" --contentSelector="article" --coverImage="https://cdn.selectdb.com/static/doris_logo_512_4903556647.png" --coverTitle="Apache Doris Docs (English)" --outputPDFFilename="Apache Doris Docs (English).pdf" --tocOnlyH1=true
            #         npx vitpress-generate-pdf --initialDocURLs="https://doris.apache.org/zh-CN/docs/dev/get-starting/" --paginationSelector=".pagination-nav__link--next" --contentSelector="article" --coverImage="https://cdn.selectdb.com/static/doris_logo_512_4903556647.png" --coverTitle="Apache Doris Docs (中文)" --outputPDFFilename="Apache Doris Docs (中文).pdf" --tocOnlyH1=true
            #         mkdir -p ./build/assets/files/
            #         cp *.pdf ./build/assets/files/
            #         ls ./build/assets/files/

            - name: Remove pdf
              run: rm -rf ./build/assets/files/*.pdf

            - name: Create GitHub Release
              uses: ncipollo/release-action@v1
              with:
                   tag: $CI_COMMIT_SHORT_SHA
                   allowUpdates: true
                   artifacts: "build/*"
                   token: ${{ github.token }}
                   generateReleaseNotes: true    
